### User signUp endpoint
POST http://localhost:3000/v1/user
Content-Type: application/json

{
    "name":"Sagun Shrestha",
"email":"admin@gmail.com",
"password":"admin",
"phone":"12312312",
"address":"bkt",
"company":"asdas"
}


### User SignIn endpoint
POST http://localhost:3000/v1/user/login
Content-Type: application/json

{
"email":"admin@gmail.com",
"password":"admin"
}

### User Profile endpoint
GET http://localhost:3000/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTYxNTE5MjY1NiwiZXhwIjoxNjE1MTkzNTU2fQ.IqbXjiAr8NTSXzpXJByZJy54219apZn11vovwtkYziY



### Token routers


### Get refreshed token
GET http://localhost:3000/v1/tokens